FROM golang:1.17-alpine AS staging

COPY . /workspace
WORKDIR /workspace
ENV GO111MODULE=on
ENV TZ=Asia/Taipei
RUN apk add bash tzdata make && make install-generator

FROM golang:1.17-alpine AS production
COPY --from=staging /go/bin /go/bin
WORKDIR /workspace

ENTRYPOINT ["generator"]